# **TITANIC SURVIVAL PREDICTION USING LOGISTIC REGRESSION**

This project focuses on predicting which Titanic passengers survived the shipwreck using Logistic Regression model.

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [15]:
from google.colab import files
uploaded = files.upload()

Saving titanic_cleaned_unscaled.csv to titanic_cleaned_unscaled (1).csv

The dataset was cleaned and processed for ML in the first week's assignment.

In [16]:
df = pd.read_csv('titanic_cleaned_unscaled.csv')

In [17]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin_Known,Embarked_Q,Embarked_S
0,1,0,3,0,22.0,1,0,7.2500,0,0,1
1,2,1,1,1,38.0,1,0,71.2833,1,0,0
2,3,1,3,1,26.0,0,0,7.9250,0,0,1
3,4,1,1,1,35.0,1,0,53.1000,1,0,1
4,5,0,3,0,35.0,0,0,8.0500,0,0,1

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    int64
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Cabin_Known  891 non-null    int64
 9   Embarked_Q   891 non-null    int64
 10  Embarked_S   891 non-null    int64
dtypes: float64(2), int64(9)
memory usage: 76.7 KB

In [19]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Cabin_Known    0
Embarked_Q     0
Embarked_S     0
dtype: int64

# **FEARTURE SELECTION**

The dataset is divided into input features (x) and a target variable (y).The features represent the passenger characteristics used by the model to learn patterns and make predictictions.

**Features (x):** Passenger information used to predict survival.

**Target (y):**The survived variable which indicates wether a passenger survived or not.

In [20]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [21]:
x.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin_Known,Embarked_Q,Embarked_S
0,1,3,0,22.0,1,0,7.2500,0,0,1
1,2,1,1,38.0,1,0,71.2833,1,0,0
2,3,3,1,26.0,0,0,7.9250,0,0,1
3,4,1,1,35.0,1,0,53.1000,1,0,1
4,5,3,0,35.0,0,0,8.0500,0,0,1

In [22]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# **TRAIN-TEST SPLIT**

The dataset is divided into training and testing sets before building the machine learning model.80% of the data is used for training and 20% is reserved for testing .A random state is specified to ensure that the same split is produced every time the coode is executed.

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((712, 10), (179, 10), (712,), (179,))

# **TRAIN THE LOGISTIC REGRESSION MODEL**

The logistics regression is a supervised machine learning model used for classification problems.In this project we will classify wether a passenger survived the Titanic disasteror not.The model learns patterns from the training data by identifying relationships between passenger characteristics and survival outcomes. The trained model will then be used to classify passengersin the testing dataset.

In [25]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# **PREDICTIONS**

**0:**Did not Survive

**1:**Survived

In [26]:
y_pred = model.predict(x_test)
print(y_pred)

[0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0
 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1
 0 0 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1
 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 0
 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 1 1]

In [27]:
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(comparison)

     Actual  Predicted
709       1          0
439       0          0
840       0          0
720       1          1
39        1          1
..      ...        ...
433       0          0
773       0          0
25        1          0
84        1          1
10        1          1

[179 rows x 2 columns]

# **MODEL EVALUATION**

The performance of the Logistic Regression model will be evaluated using the Accuracy Score. The accuracy measures the proportion of correctly classified abservations out of the total number of observations.A higher accuracy score indicates that the model correctly predicts passenger survival more often.The accuracy score provides an overall measure of the model's classification performance on the testing dataset.

In [28]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8044692737430168

# **CONCLUSION**

The Logistic Regression model achieved an accuracy score of approximately 80.44%, meaning it correctly predicted the survival outcome for about 80.44% of the passengers in the testing dataset. This indicates that the model was able to identify meaningful patterns in the passenger data and make reliable predictions.

Overall, this project provided practical experience in the complete machine learning workflow, including data preparation, feature selection, model training, prediction, and evaluation. It also demonstrated the importance of proper preprocessing and model evaluation when building classification models.